language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "0.10"
  - "0.12"
  - iojs

script:
  - npm run jshint
  - npm run test-cov

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js